### ISSUE TITLE
autoreconf -i fails due to missing m4/ for 'exsid'

### ISSUE THREAD

**Issue by Compyx** [libsidplayfp/libsidplayfp#10]
After cloning and running `autoreconf -i`, I get:
```
aclocal: error: couldn't open directory 'src/builders/exsid-builder/driver/m4': No such file or directory
autoreconf: aclocal failed with exit status: 1
```

Am I missing something?

**Comment by drfiemost** [comment]
Yep, you need to checkout with the option --recurse-submodules or just do a "git submodule init" and "git submodule update" in the exsid-driver directory

**Comment by Compyx** [comment]
Yep, that did the trick. Thanks.

**Comment by drfiemost** [comment]
OK, README updated
