### ISSUE TITLE
residfp: make uCox tunable

### ISSUE THREAD

**Issue by drfiemost** [libsidplayfp/libsidplayfp#101]
I've added a function to tweak it for each composer (as in our previous discussion), and it's a multiplier between 0.05 and 2.0. That value gets multiplied by 20e-6, and there are no crashes. You may have encountered a division by zero or something like that.

```uCox = std::clamp ( adjustment, 0.05, 2.0 ) * 20e-6;```

I'm currently adjusting the range (that's what this parameter seems to represent), and the results are much better than adjusting the DAC offset.

Every single tune I've tried so far (a couple hundred) sounds much better than before. It's insane.

Let me know if you would like some examples (before and after) and which tunes you would like. The Martin Galway stuff is unnecessary, as their current filter settings have been tweaked for "Wizball".

_Originally posted by @reFX-Mike in https://github.com/libsidplayfp/libsidplayfp/discussions/100#discussioncomment-7873042_

**Comment by drfiemost** [comment]
@reFX-Mike do you plan to test the uCox value for 8580 too? Otherwise we can freeze the API and start thinking about the 2.7 release.

**Comment by reFX-Mike** [comment]
All 8580 tunes sound fine to me with defaults, so I don’t think it’s necessary.

**Comment by drfiemost** [comment]
Good! Let's switch to the beta phase then
