### ISSUE TITLE
Emulate oscillator leakage

### ISSUE THREAD

**Issue by drfiemost** [libsidplayfp/libsidplayfp#102]
Seen it mentioned at [CSDb](https://csdb.dk/forums/?roomid=14&topicid=163246)

> An oscillator's volume level being 0 still lets some of the oscillator's signal through. You can hear this in many demo recordings on YouTube. When a tune has faded out, you can still hear the SID voices very faintly holding the last sound register values.

It's likely related to the MDAC, maybe a DC offset or something.

Would be good to have a sample tune to verify the effect.

**Comment by reFX-Mike** [comment]
Technically, this would be possible to emulate, but I think it should be optional.

Here is my thought process: on original hardware (not emulation, not reloaded boards, etc.), the analog amp stages were so bad, the amount of noise and hum they introduced so loud, that nobody could actually hear that leakage. It was completely buried under the noise and hum.

So emulating only the leakage, but not the hum or noise, would make the very clean output of libsidplayfp sound "wrong". It would be distracting and cause "this doesn't sound like a real C64 at all" comments from users.

I'm actually in the early stages of adding another (optional) FX pass to my SID player, so it sounds more "authentic", but adding hum, noise, and shape using ten individual notch filters to simulate 2-3 inch speaker (those tiny ones on the side of a 1084).

To idea is to have three output modes:

- pure (raw libsidplay output)
- authentic (added hum, noise, and notches)
- enhanced (like pure, but with stereo-widening, delay, reverb, and a hint of noise for "warmth")

**Comment by drfiemost** [comment]
Yep, there's a lot of background noise on a real C64, it also might have a dithering effect.
Anyway I'm curious about the real cause, it doesn't seem related to the single voice but maybe to the global volume.

**Comment by drfiemost** [comment]
Another discussion with a test program https://csdb.dk/forums/?roomid=14&topicid=164372#164378

**Comment by mrdudz** [comment]
VICE actually (optionally) emulates (some of) the background noise (the portion that was needed to make "vic samples" work).

**Comment by reFX-Mike** [comment]
Couldn't that easily be achieved by not letting the envDac reach zero?

e.g. ```return wavDac * ( envDac * 0.95f + 0.05f );```

**Comment by drfiemost** [comment]
Sure, you can force envDAC[0] to a small value greater than zero.
But I'm curious about the real cause behind this; when envelope is zero the output is connected to Vref (8580) or Vcc (6581) while the waveform is completely disconnected. Maybe the transistors still let some of the current through? Or is there some electrical interference?
I've been thinking about some weird behavior of the envelope generator when the counter reaches zero at the same time when the sustain comparator triggers but from a quick glance at the schematics it doesn't seem plausible.

**Comment by reFX-Mike** [comment]
No transistor is perfect. Especially the ones from the early 80s...

https://en.wikipedia.org/wiki/Subthreshold_conduction

**Comment by reFX-Mike** [comment]
So even though the waveform is completely disconnected, it's not that "complete".

**Comment by drfiemost** [comment]
Interesting... 
Didn't have the time to check yet, does the effect gradually fade away or is it constant?
In the latter case setting `envDAC[0]` would do the trick.

**Comment by reFX-Mike** [comment]
It’s constant. Basically some current makes it through the isolator, and since it’s not a capacitor it’s not building up a higher resistance over time.

**Comment by reFX-Mike** [comment]
After reading through it again, I was mistaken. It seems to fall off over time, but how long that takes depends on the voltages and the material, etc., so we have to measure some test programs and see how quickly it becomes quiet.

But since we're talking SID from the 80s here, it could be that even in ideal situations, it will never reach zero.

**Comment by reFX-Mike** [comment]
If the fall off is fast enough (maybe a few hundred nano-seconds) but still never reaches zero, then for all practical purposes, nobody could even hear the fall off from 0.01 to 0.008 volts, so making it a constant might be easiest. Jammer wanted to do some tests in his free time, so maybe he can shed some light on observed behaviour.

**Comment by drfiemost** [comment]
In that case something like this can work.

```patch
--- a/src/builders/residfp-builder/residfp/Dac.cpp
+++ b/src/builders/residfp-builder/residfp/Dac.cpp
@@ -37,6 +37,10 @@ Dac::~Dac()
 
 double Dac::getOutput(unsigned int input) const
 {
+    // DAC leakage
+    if (input == 0)
+        return dac[0] / 2.;
+
     double dacValue = 0.;
 
     for (unsigned int i = 0; i < dacLength; i++)
```

**Comment by reFX-Mike** [comment]
This works fine here, and for testing I multiplied with 2.0, so I could hear the leakage better. It was hard to find tunes that let the voices die all the way, but it was very clearly working.

This has the side affect of also adding leake to the oscs and the filter-cutoff, but no ill effects so far. I've tested Wizball, and it sounds exactly the same as before.

**Comment by drfiemost** [comment]
> This works fine here, and for testing I multiplied with 2.0, so I could hear the leakage better. It was hard to find tunes that let the voices die all the way, but it was very clearly working.

Good. I think adding background noise could deliver a dithering effect which would make it more audible.

BTW Here is the test prog mentioned in the CSDb discussion above:
[leak_test.prg.zip](https://github.com/libsidplayfp/libsidplayfp/files/14143391/leak_test.prg.zip)

> VICE actually (optionally) emulates (some of) the background noise (the portion that was needed to make "vic samples" work).

@mrdudz what kind of noise is it? Where can I find the code?

> This has the side affect of also adding leake to the oscs and the filter-cutoff, but no ill effects so far. I've tested Wizball, and it sounds exactly the same as before.

Yes, as the DAC are built in the same way the leakage affect them all.

**Comment by mrdudz** [comment]
> @mrdudz what kind of noise is it? Where can I find the code?

It's a specific kind of noise which is completely unrelated to the SID - and even works when the audio output is not even connected to the monitor :) What happens in reality, is that the audio amplifier in the monitor is "modulated" by the magnetic field of the tube, so by changing the output signal in rapid ways, you can produce audible noise. This was demonstrated in the "Vicious SID" demo.

This is the code in VICE: https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/video/video-sound.c

What it does is basically taking the luma signal and converting that into a sample. With some added noise floor on top, which more or less reproduces the screeching noise you can hear when you crank up the volume on the monitor and switch the background to white. Obviously this is very much NOT what really happens, but good enough to make the "VIC Samples" in "Vicious SID" work (and otherwise pretty much unwanted =P)

To enable it in VICE, use Display->VIC-II->misc->Audio leak emulation (its off by default)

then poke53280,1:poke53281,0 and you'll notice the familiar noise (also crank up volume)

**Comment by reFX-Mike** [comment]
I wouldn't emulate the induction noise generated by the magnetic field of the tube onto the speaker wire. It may be a neat demo for people using real hardware, but at the end of the day, it's a side-effect of that particular combination (real CRT with unshielded audio cable, cheap amp inside said monitor, etc.) and is highly undesirable.

What I would rather do is add a small amount of white noise to the chip-output, as all analog circuitry introduces it to some degree. You just generate random values, scale them down to be almost inaudible, and add it to the output. The scale should be adjustable, so you can go from zero noise (like it is now) all the way up to clearly audible and even a bit annoying (a bit exaggerated). Somewhere in the middle is the reality for the real chip.

**Comment by mrdudz** [comment]
Yes, inside reSID this is what should happen, i guess.

That said, what is actually a more present source of noise on real hardware is bus noise - for example crank up the volume a bit, then load something from disk. you can then clearly hear bursts of noise, which are related to the IEC transfers :) But again, this isn't something that should be in reSID, but in the C64 emulator (maybe, perhaps, or maybe not :-))

**Comment by reFX-Mike** [comment]
I agree that the bus noise should not be emulated in reSID/reSIDfp. No access is happening to the serial port while listening to SID tunes from the HVSC.

For VICE, it might be neat to recreate the nostalgia of sitting in front of the real hardware, 40 years ago.

**Comment by reFX-Mike** [comment]
BTW, it's sufficient to generate the white-noise at the audio-output sample rate, as a post-process so to speak:

```
static int64 seed = 12345678;

int nextRand ()
{
    seed = (int64) (((((uint64) seed) * 0x5deece66dLL) + 11) & 0xffffffffffffLL);
    return (int) (seed >> 16);
}
```

If you visualize it on a 2D map as a bitmap, you will see some form of repeating behavior, but as an audio-signal white noise generator, it's more than sufficient, and it's super-fast.

We should generate two signals for stereo SIDs, as each real chip contributes its own noise.

**Comment by drfiemost** [comment]
Tried with brown noise, a bit less harsh:

```c
    inline short brownNoise() const
    {
        noise_seed = (16843009 * noise_seed + 826366247);
        old_noise += static_cast<short>(((noise_seed >> 16) & 0x00ff) - 0x80);
        if (old_noise > 127)
            old_noise = 127;
        else if (old_noise < -128)
            old_noise = -128;
        return old_noise;
    }
```
Can't tell if the result is good enough. Need to check some real recording and look at the noise level and spectrogram.

**Comment by drfiemost** [comment]
Implementation is ready (#119), feedback is welcome.
I'll open a separate issue for a possible noise emulation in a future version.

**Comment by reFX-Mike** [comment]
Should the leakage strength be adjustable if listeners prefer a "cleaner" experience?

**Comment by drfiemost** [comment]
If we can determine a sane range why not? And it would be nice to know if the old and new revisions have different levels of leaking.
Feel free to open a new issue.
