### ISSUE TITLE
Build: add the configure check for the xa cross-assembler presence

### ISSUE THREAD

**Issue by Wohlstand** [libsidplayfp/libsidplayfp#12]
Recently I tried to build the library, and I got the error that the `xa` command is missing:

```
o65file=`echo src/sidtune/sidplayer1.bin | sed 's/bin/o65/'`;\
xa -R -G src/sidtune/sidplayer1.a65 -o $o65file &&\
od -v -An -w8 -tx1 $o65file | sed -re 's/[[:alnum:]]+/0x&,/g' > src/sidtune/sidplayer1.bin &&\
rm -f $o65file
/bin/bash: строка 1: xa: команда не найдена
make: *** [Makefile:2993: src/sidtune/sidplayer1.bin] Ошибка 127
```

I figured out that it needs to install the xa65 package to get it to work. I think you should add the configure-level check to verify the presence of the `xa` assembler to don't confuse users when the build-level "xa command not found" error gets up.

**Comment by drfiemost** [comment]
Actually xa is only required for bootstrapping so no need for a check at build time.
I've updated the README in 0eafc33 to mention the dependency

**Comment by Wohlstand** [comment]
Thanks!
