### ISSUE TITLE
Possible performance optimization in resampler class

### ISSUE THREAD

**Issue by reFX-Mike** [libsidplayfp/libsidplayfp#123]
Right now the softclip happens at the input of both sinc-resamplers to keep the buffer depth to 16-bit, and then another softclip at the output of the second sinc-resampler. Wouldn't it be more efficient to store the sinc-resampler buffers as 32-bit ints and then do the softclip only once at the output?

**Comment by drfiemost** [comment]
Tried with both the sample table and the fir table as int and there's a slight degradation in performance.
Keeping the fir table as short (so the function becomes `int convolve(const int* a, const short* b, int bLength)`) gives comparable timings so it may be an option to consider in the short term. Eventually I'd like to move to float though.

**Comment by reFX-Mike** [comment]
So the audio-buffers in general would all be floats with a range from -1.0 to +1.0? Like in professional DAWs and audio-plugins?

**Comment by drfiemost** [comment]
They will be converted to signed 16bit at the end but may also give an option for floats in the future.

**Comment by drfiemost** [comment]
Available for testing in #124

**Comment by reFX-Mike** [comment]
On my machine, this is measurably slower, and since only very few SID tunes would be affected by double-clipping them, I would leave it as int16_t for now.

**Comment by drfiemost** [comment]
Hmmm, that's disappointing. Maybe a SIMD verision would help.
This is what I get on my CPU: https://godbolt.org/z/zsT3M3h4d

**Comment by reFX-Mike** [comment]
If I enabled SSE 4.1, I get very similar code with Clang 18.1 that is now actually faster with the int32_t instead of the int16_t! So even with SSE 4.1 enabled, the int16_t convolution is slower than with int32_t. Amazing.

So I guess ultraSID needs a SSE 4.1 capable CPU now.

```MUSICIANS/Hubbard_Rob/Spellbound.sid```

Using int16_t, SSE3, and 3x softClip: 13.8 times real time
Using int32_t, SSE4.1, and 1x softClip: 14.5 times real time.

Not a huge increase, but totally worth it.

**Comment by drfiemost** [comment]
Well, SSE4.1 is in x86-64-v2, not that big requirement:
https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels

**Comment by reFX-Mike** [comment]
Yep, I fully agree. My day job is audio programming for the professional audio-plugin market, and some users are VERY conservative regarding their hardware and software choices, so we limit ourselves to SSE3.

We will now safely enable SSE4.1 and SSE4.2 for our newer updates.

**Comment by emoon** [comment]
I think going for SSE4.2 as baseline is good. SSE4.2 added lots of useful instructions esp when it comes to integers.

**Comment by reFX-Mike** [comment]
Now if we could agree that C++17 is also a good baseline and replace some old concepts with newer C++ code... 😉

**Comment by emoon** [comment]
Also for the code above helping the compiler out (again) gives some better code https://godbolt.org/z/Yo7osTEEW

**Comment by reFX-Mike** [comment]
Does the manual unrolling measurably increase performance in this case?

**Comment by emoon** [comment]
I see that clang actually makes a vectorized loop correctly without the manual unroll so it may or may not matter here. The reason in can help even if the CPU is out of order it may help due to less dependent instructions, but I haven't measured.

**Comment by drfiemost** [comment]
> Also for the code above helping the compiler out (again) gives some better code https://godbolt.org/z/Yo7osTEEW

It gets slightly worse here with gcc.

**Comment by drfiemost** [comment]
Restored the SSE version with intrinsics, seems to work fine.
