### ISSUE TITLE
libsidplayfp 2.7.0: Undefined type (CombinedWaveforms)

### ISSUE THREAD

**Issue by stuerp** [libsidplayfp/libsidplayfp#125]
I tried to upgrade to v2.7.0 but out of the box it does not compile with VS 2022 because of an undefined type "CombinedWaveforms".  There is however a method called ReSIDfp::CombinedWaveforms().

What am I missing? Any help is much appreciated.

**Comment by drfiemost** [comment]
It's an `enum`, defined in `siddefs-fp.h
`
https://github.com/libsidplayfp/libsidplayfp/blob/c747cf5a0f568aea8c8298a21dc1c4a38563fd04/src/builders/residfp-builder/residfp/siddefs-fp.h.in#L46

**Comment by stuerp** [comment]
> It's an `enum`, defined in `siddefs-fp.h `
> 
> https://github.com/libsidplayfp/libsidplayfp/blob/c747cf5a0f568aea8c8298a21dc1c4a38563fd04/src/builders/residfp-builder/residfp/siddefs-fp.h.in#L46

Hmm, I overlooked that. Since I use VS 2022 I don't (want to) have the toolchain to process *.in files. Could accommodate VS builds more easily in a feature release, please?
