### ISSUE TITLE
Some v2.7 sound weirdness during tune fadeout

### ISSUE THREAD

**Issue by bytespiller** [libsidplayfp/libsidplayfp#126]
I've noticed some sound weirdness in the libsidplayfp v2.7 that isn't present in the v2.6, specifically in situations at the end of the tune when it's _fading out_.

- **Example 1**
Weird high frequency tone similar to tinnitus or ringing in the ear at the end of the song `/MUSICIANS/T/Tel_Jeroen/Skypeople.sid`
  - Repro: `sidplayfp.exe -b2:20 Skypeople.sid`
- **Example 2**
Relatively loud white noise (in previous version there is a perfect silence) at the end of the subsong 2 of `/MUSICIANS/C/Cadaver/Metal_Warrior_2.sid`
  - Repro: `sidplayfp.exe -o2 -b3:20 Metal_Warrior_2.sid`

(repro timestamps are sufficiently before the occurrence)

**Comment by drfiemost** [comment]
This is likely the oscillator leakage. It should be there on the real chip too, although the level might differ and partially drowned in the background noise.
Will give a try when I have some time.

**Comment by reFX-Mike** [comment]
It should be adjustable, and maybe 0 should be the default.

**Comment by drfiemost** [comment]
Recordings from exSID
[leakage_samples.zip](https://github.com/libsidplayfp/libsidplayfp/files/15325995/leakage_samples.zip)

**Comment by bytespiller** [comment]
So it's legit!

Is there any way for a client application to adjust the oscillator leakage in the current version?

**Comment by reFX-Mike** [comment]
> Is there any way for a client application to adjust the oscillator leakage in the current version?

Unfortunately no. I've added that functionality to my branch, but it has other changes you might not like, so I guess we have to wait for @drfiemost to add it to the official version.

**Comment by drfiemost** [comment]
Not yet, see #122 
In the meanwhile I'll downtune the default for the next release

**Comment by bytespiller** [comment]
Perhaps the ability to enable/disable it would be sufficient (rather than exposing the leakage parameter if it's problematic) so client players could offer the "Ideal chip" toggle.

**Comment by bytespiller** [comment]
Closing this issue as completed since the original topic's concern is resolved (details on leakage levels can be discussed in the #122 as needed).
