### ISSUE TITLE
Accuracy issue since v2.6 on some files (ReSIDfp)

### ISSUE THREAD

**Issue by yoyofr** [libsidplayfp/libsidplayfp#127]
Hi,
I'm using libsidplayfp in modizer as primary playback library for SID and some users reported regression since v2.6
I was given the following hardware recording as reference https://www.youtube.com/watch?v=ylw8TjlwS9w&authuser=1 and if you listen to the first 20 seconds you'll notice significant gaps when using ReSIDfp between 2.5 (or former) and 2.6/2.7

**Comment by drfiemost** [comment]
Plays fine with the WEAK or STRONG cw model but not with the AVERAGE.
Tune uses pulse+triangle and ringmod:

```
| Frame | Freq Note/Abs WF ADSR Pul | Freq Note/Abs WF ADSR Pul | Freq Note/Abs WF ADSR Pul | FCut RC Typ V |
+-------+---------------------------+---------------------------+---------------------------+---------------+
|     0 | 027D (D-1 8E) 80 0000 060 | 0000  ... ..  08 0F0F 000 | 03BB (A-1 95) 80 0000 060 | 0000 02 Off F |
|     1 | 27DF (D-5 BE) 40 .... 050 | E18F  G#7 DC  31 F446 800 | 3BBE (A-5 C5) 40 .... 050 | .... 00 ... . |
|     2 | 1DDF (A-4 B9) .. .... 080 | ....  ... ..  .. .... 83F | 2CC1 (E-5 C0) .. .... 080 | .... .. ... . |
|     3 | 027D (D-1 8E) 80 .... 050 | ....  ... ..  .. .... 87E | 03BB (A-1 95) 80 .... 050 | .... .. ... . |
|     4 | 1B01 (G#4 B8) 54 .... 080 | ....  ... ..  .. .... 8BD | FE02 (B-7 DF) 54 .... 080 | .... .. ... . |
|     5 | ....  ... ..  .. .... 050 | ....  ... ..  .. .... 8FC | ....  ... ..  .. .... 050 | .... .. ... . |
```

You can force the Strong model for now which seems to produce better results (see https://github.com/libsidplayfp/sidplayfp/issues/34 too)

**Comment by reFX-Mike** [comment]
I don't think any musician with a weak or average CW model would use combined waveforms, as they are too quiet. In my version the default is strong for both (6581/8580) and all tested songs sound MUCH better now.

**Comment by yoyofr** [comment]
thanks, using strong CW model indeed sounds good. Any way to detect automatically which one to use or shall I force strong as default one ? not sure to understand the decision criteria to match best accuracy

**Comment by drfiemost** [comment]
I'll make STRONG the default. It's a bit weird that the WEAK sounds ok too, maybe should compare the RMS for each combination.

Anyway, for future reference the tune is `/MUSICIANS/P/Psych858o/Funky_Witch.sid`

**Comment by yoyofr** [comment]
ok thanks
