### ISSUE TITLE
missing .bin files in repo

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [libsidplayfp/libsidplayfp#128]
sidplayer1.bin and sidplayer2.bin inside src/sidtune are missing from the repo.

**Comment by yoyofr** [comment]
I think it's because in the repp only the 6502 assembly source code is kept. You need to either compile it yourself (cf build instruction) or download a release source code (ex: 2.7.0) in which it is already done.

**Comment by drfiemost** [comment]
As yoyofr said; generated files are not meant to be in the source repo.
In fact psiddrv.bin should be removed too.

**Comment by drfiemost** [comment]
Yes, or maybe use CPack to pregenerate it before packaging.
You need `xa` from xa65 and `od` from GNU coreutils:

```
xa -R -G psiddrv.a65 -o psiddrv.o65
od -v -An -w8 -tx1 psiddrv.o65 | sed -re 's/[[:alnum:]]+/0x&,/g' > psiddrv.bin
```
