### ISSUE TITLE
configure --with-exsid with exsid package installed fails

### ISSUE THREAD

**Issue by OPNA2608** [libsidplayfp/libsidplayfp#13]
If `libexsid` itself is found to already be installed, then this test here only sets `build_exsid_builder`.
https://github.com/libsidplayfp/libsidplayfp/blob/0eafc3329be260fba694a503aec7eae66d5b5b1e/configure.ac#L279-L282

However the check later on asks whether `--with-exsid=yes` was passed and `build_exsid_driver` from the tests for `ftd2xx` or `libftdi1` returned yes instead. This errors if `libexsid` was found and thus doesn't need to be built. (There's also a typo in the error message that's emitted there)
https://github.com/libsidplayfp/libsidplayfp/blob/0eafc3329be260fba694a503aec7eae66d5b5b1e/configure.ac#L307-L310

Configure output:
> ```
> checking pkg-config is at least version 0.9.0... yes
> checking for libexsid >= 2.0... yes
> configure: error: Neither libexid nor ftd2xx nor libftdi1 found
> ```

Replacing `build_exsid_driver` in the later check with `build_exsid_builder` makes it compile fine.

**Comment by drfiemost** [comment]
Fix queued for next release, thank you for reporting and for the thorough explanation
