### ISSUE TITLE
Impossible to build LibSIDPlayFp 2.7.0 and 2.7.1

### ISSUE THREAD

**Issue by TCH68k** [libsidplayfp/libsidplayfp#135]
I used the tar gzip archives, downloaded from the releases list. No `configure`, so i did `autoreconf -i`, but it fails with the following error message:
```
aclocal: error: couldn't open directory 'src/builders/exsid-builder/driver/m4': No such file or directory
autoreconf: error: aclocal failed with exit status: 1
```
If i replace the line
```
AC_CONFIG_MACRO_DIRS([m4 src/builders/exsid-builder/driver/m4])
```
with
```
AC_CONFIG_MACRO_DIRS([m4])
```
then the error is the following:
```
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:273: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
```
`autoconf --version`: `autoconf (GNU Autoconf) 2.71`

I don't need exsid support, but since i could not disable it, i installed `libfdti1`. No difference.

**Comment by drfiemost** [comment]
Just download the official tarball (https://github.com/libsidplayfp/libsidplayfp/releases/download/v2.7.1/libsidplayfp-2.7.1.tar.gz), it contains everything required.
The github generated archives are basically useless.

**Comment by mywave82** [comment]
Yeah, its a shame that the auto-generated Source.tar.gz files do not include git submodules. Are you able to build the source code @TCH68k, using the link @drfiemost provided?

**Comment by TCH68k** [comment]
I see, _"Source code (zip)"_ and _"Source code (tar.gz)"_ are generated archives which lack stuff and _"libsidplayfp-2.7.1.tar.gz"_ is the official package which works. And it did, without errors, or any other problems. Thank you guys for enlightening me.
