### ISSUE TITLE
Very low voice volume with bandpass filter and ENGINE = RESIDFP

### ISSUE THREAD

**Issue by jansalleine** [libsidplayfp/libsidplayfp#143]
As stated in the title. When setting ENGINE = RESID the tune sounds just fine.

This is the tune where I encountered the problem:
https://csdb.dk/sid/?id=51734
https://hvsc.csdb.dk/MUSICIANS/S/Spider_Jerusalem/Easyriff.sid

Played back with: **Sidplayfp V2.9.0, Libsidplayfp V2.9.0**.

All other settings are left untouched:
```
[Audio]
Frequency = 48000
Channels = 
BitsPerSample = 

[Emulation]
Engine = RESIDFP
C64Model = 
ForceC64Model = 
DigiBoost = 
CiaModel = 
SidModel = 
ForceSidModel = 
UseFilter = 
FilterBias = 
FilterCurve6581 = 
FilterCurve8580 = 
PowerOnDelay = 
Sampling = 
ResidFastSampling = 
FilterRange6581 = 
CombinedWaveforms =
```

**Comment by drfiemost** [comment]
It's not the filter, it's the triangle+saw waveform.
If you set:
`CombinedWaveforms = WEAK`
it sounds more like intended.

**Comment by jansalleine** [comment]
> It's not the filter, it's the triangle+saw waveform. If you set: `CombinedWaveforms = WEAK` it sounds more like intended.

Yes, you're right. Thanks!
But shouldn't this be the default then? I just checked my real machine with 8580: there it also sounds like with the WEAK setting turned on. Or does that differ on a "per tune" basis?

**Comment by drfiemost** [comment]
I've properly measured the waveform RMS and updated the parameters accordingly.
Should be ok now in master with the default AVERAGE setting.
