### ISSUE TITLE
Soloing channels doesn't preserve all sync effects.

### ISSUE THREAD

**Issue by acrouzet** [libsidplayfp/libsidplayfp#146]
sidplayfp seems to disable sync when soloing channels 1 and 3 when all channels have sync enabled.

MUSICIANS\D\Deek\Googachild.sid is an example of a tune where this happens.

**Comment by reFX-Mike** [comment]
@drfiemost if you use a voice-mask in the new filter::clock function, this will be avoided and thus fixed.

**Comment by drfiemost** [comment]
Should be fixed in master by preserving the low nibble of the control register, i.e. using waveform $0 for muted voices.

**Comment by ruby-R53** [comment]
just tried it, it works!
