### ISSUE TITLE
High pitched overtones

### ISSUE THREAD

**Issue by PM250B** [libsidplayfp/libsidplayfp#156]
I noticed when I play waveforms. high pitched overtones are generated which should not be there. I noticed it with the $11 waveform. 8580 emulation.
[high.zip](https://github.com/user-attachments/files/17268850/high.zip)

**Comment by acrouzet** [comment]
Can you provide a recording yourself? I don't hear it myself.

**Comment by bytespiller** [comment]
I think I can hear it as an upwards-sweeping sound but it's super faint and volume has to be cranked way up.
For example right in the first 2 seconds (and throughout).

I've attached the first 3 seconds amplified in the Audacity (but it's still quite faint).
[high_3s_amplified.zip](https://github.com/user-attachments/files/17303300/high_3s_amplified.zip)

If that's what it is, for the provided SID file (which uses only voice 1) it happens only on 8580 emulation, and toggling the filter, digis (v2.10) and digiboost has no effect on it. Tried it in v2.5 (sidplayfp player, not lib) too.

**Comment by PM250B** [comment]
Thanks. Yep, exactly. I was going to prepare it during the day too. It happens everywhere reSID is used. I noticed it when I wanted to test some base drums in the GT2 fork with the latest reSID emulation.

**Comment by drfiemost** [comment]
> If that's what it is, for the provided SID file (which uses only voice 1) it happens only on 8580 emulation, and toggling the filter, digis (v2.10) and digiboost has no effect on it. Tried it in v2.5 (sidplayfp player, not lib) too.

That's weird, triangle waveform is the same for both models. Does it happen with both resid and residfp?

**Comment by bytespiller** [comment]
The recording I've provided is with residfp, but I've tried with resid (which I should have in the first place, since the OP mentions it explicitly) and with resid it's even more pronounced and easier to hear whatever it is.

I'm not 100% sure what the expected output should be and if there is an actual issue at all since the waveform indeed looks clean. Somebody with more knowledge should perhaps look into the OP's provided SID file and see what the tune is trying to do vs. the output.

**Comment by acrouzet** [comment]
To me it sounds like quantization errors, which is odd because sidplayfp is floating point.

**Comment by drfiemost** [comment]
> To me it sounds like quantization errors, which is odd because sidplayfp is floating point.

Yeah, it may be the case when we truncate the filter output to int here:
https://github.com/libsidplayfp/libsidplayfp/blob/114744ddf886067426883884427671915e72b733/src/builders/residfp-builder/residfp/SID.h#L335

**Comment by drfiemost** [comment]
This quick&dirty patch should fix it, can you confirm?

```diff
diff --git a/src/builders/residfp-builder/residfp/FilterModelConfig.cpp b/src/builders/residfp-builder/residfp/FilterModelConfig.cpp
index ae9b8027..33455664 100644
--- a/src/builders/residfp-builder/residfp/FilterModelConfig.cpp
+++ b/src/builders/residfp-builder/residfp/FilterModelConfig.cpp
@@ -47,7 +47,8 @@ FilterModelConfig::FilterModelConfig(
     norm(1.0 / denorm),
     N16(norm * ((1 << 16) - 1)),
     voice_voltage_range(vvr),
-    voice_DC_voltage(vdv)
+    voice_DC_voltage(vdv),
+    m_rand(257254)
 {
     setUCox(ucox);
 
diff --git a/src/builders/residfp-builder/residfp/FilterModelConfig.h b/src/builders/residfp-builder/residfp/FilterModelConfig.h
index 45ef393c..911d24a5 100644
--- a/src/builders/residfp-builder/residfp/FilterModelConfig.h
+++ b/src/builders/residfp-builder/residfp/FilterModelConfig.h
@@ -36,6 +36,33 @@ namespace reSIDfp
 
 class FilterModelConfig
 {
+private:
+    // random number generator for dithering
+    class randomLCG
+    {
+    private:
+        mutable int rand_seed;
+
+    public:
+        randomLCG(int seed) :
+            rand_seed(seed)
+        {}
+
+        int get() const
+        {
+            rand_seed = (214013 * rand_seed + 2531011);
+            return static_cast<int>((rand_seed >> 16) & 0xffff);
+        }
+    };
+
+    mutable float m_oldRandomValue = 0.f;
+    float triangularDithering() const
+    {
+        const float prevValue = m_oldRandomValue;
+        m_oldRandomValue = m_rand.get()/65535.f;
+        return m_oldRandomValue - prevValue;
+    }
+
 protected:
     /// Capacitor value.
     const double C;
@@ -75,6 +102,9 @@ protected:
     /// Reverse op-amp transfer function.
     unsigned short opamp_rev[1 << 16]; //-V730_NOINIT this is initialized in the derived class constructor
 
+private:
+    randomLCG m_rand;
+
 private:
     FilterModelConfig(const FilterModelConfig&) = delete;
     FilterModelConfig& operator= (const FilterModelConfig&) = delete;
@@ -235,7 +265,7 @@ public:
     {
         const double tmp = N16 * (value - vmin);
         assert(tmp > -0.5 && tmp < 65535.5);
-        return static_cast<unsigned short>(tmp + 0.5);
+        return static_cast<unsigned short>(tmp + triangularDithering());
     }
 
     inline unsigned short getNormalizedCurrentFactor(double wl) const
```

**Comment by drfiemost** [comment]
Another try, faster and cleaner, using a small prerendered buffer of noise:

```diff
--- a/src/builders/residfp-builder/residfp/FilterModelConfig.h
+++ b/src/builders/residfp-builder/residfp/FilterModelConfig.h
@@ -24,6 +24,7 @@
 #define FILTERMODELCONFIG_H
 
 #include <algorithm>
+#include <random>
 #include <cassert>
 
 #include "OpAmp.h"
@@ -36,6 +37,23 @@ namespace reSIDfp
 
 class FilterModelConfig
 {
+private:
+    class Randomnoise
+    {
+    private:
+        double buffer[1024];
+        mutable int index = 0;
+    public:
+        Randomnoise()
+        {
+            std::uniform_real_distribution<double> unif(0., 1.);
+            std::default_random_engine re;
+            for (int i=0; i<1024; i++)
+                buffer[i] = unif(re);
+        }
+        double getNoise() const { index = (index + 1) & 0x3ff; return buffer[index]; }
+    };
+
 protected:
     /// Capacitor value.
     const double C;
@@ -75,6 +93,9 @@ protected:
     /// Reverse op-amp transfer function.
     unsigned short opamp_rev[1 << 16]; //-V730_NOINIT this is initialized in the derived class constructor
 
+private:
+    Randomnoise rnd;
+
 private:
     FilterModelConfig(const FilterModelConfig&) = delete;
     FilterModelConfig& operator= (const FilterModelConfig&) = delete;
@@ -235,7 +256,7 @@ public:
     {
         const double tmp = N16 * (value - vmin);
         assert(tmp > -0.5 && tmp < 65535.5);
-        return static_cast<unsigned short>(tmp + 0.5);
+        return static_cast<unsigned short>(tmp + rnd.getNoise());
     }
 
     inline unsigned short getNormalizedCurrentFactor(double wl) const
```

Anyway, one more reason to move the whole analog part to floats.

**Comment by bytespiller** [comment]
FWIW I've tried the second version only and I can confirm the audible high pitch for 8580 is greatly reduced and is not perceptible unless looking for it specifically in an artificially amplified signal. This cleaner version when compared with previous one reveals that even the 6581 had a barely perceptible high pitched tone (which is also gone with this change).

**Comment by PM250B** [comment]
The issue appears to persist in the current release of Vice, as evidenced by the results of a quick test I conducted.

**Comment by PM250B** [comment]
While the reSID-FP sounds good, the normal reSID is still affected by disturbing background noise. Unfortunately, this is tragic because important emulators such as VICE and Denise, as well as SID trackers, use reSID.

**Comment by mrdudz** [comment]
@PM250B yfi - i have just added support for residfp to VICE, check it out :)

**Comment by PM250B** [comment]
> [@PM250B](https://github.com/PM250B) yfi - i have just added support for residfp to VICE, check it out :)

Well done. 👍

I had a quick go at testing the reSIDfp and played around with the sliders. The 6581 filter seems to suffer from severe aliasing. All sorts of strange distortions that blend in with the normal 6581 distortion.
