### ISSUE TITLE
Digiboosting 8580 doesn't work

### ISSUE THREAD

**Issue by acrouzet** [libsidplayfp/libsidplayfp#157]

**Comment by bytespiller** [comment]
In what way exactly is "doesn't work" manifesting for you?

I've tried it in v2.10 by forcing the 8580 with Digiboost enabled/disabled and there is a clear difference with the tune for which I know has digi samples right at the beginning (and throughout): `\MUSICIANS\T\Tel_Jeroen\Afterburner.sid`

- `sidplayfp.exe -mnf --digiboost Afterburner.sid`
  - Digi part of the tune is loud.
- `sidplayfp.exe -mnf Afterburner.sid`
  - Digi part of the tune is subdued.

**Comment by acrouzet** [comment]
Try MUSICIANS/H/Huelsbeck_Chris/To_be_on_Top.sid  the digi is barely audible at times.

**Comment by drfiemost** [comment]
It depends on what kind of sample technique is used, AFAIK digiboost only work for volume based digis.

**Comment by acrouzet** [comment]
All the tunes I tested use volume-based digi.

**Comment by drfiemost** [comment]
So it works for some tunes but not for others. The question is then what happens with a real chip.

**Comment by drfiemost** [comment]
Whoops, should be fixed now in master.

**Comment by drfiemost** [comment]
Queued for next release in the following days.
Thanks!
