### ISSUE TITLE
Is the "average" 8580 saw+pulse waveform supposed to be this thin and quiet

### ISSUE THREAD

**Issue by acrouzet** [libsidplayfp/libsidplayfp#160]
![image](https://github.com/user-attachments/assets/e3338161-2ea7-4062-a19a-4e9f5d39b045)
Top is "average" 8580 saw+pulse, bottom is "weak".

**Comment by PM250B** [comment]
"The default 'average' setting doesn't seem to be correct to me. I compared it with a few 8580 songs, and it sounds wrong. In quick tests, 'weak' (dirtier?) gave the desired result.

The only question is whether this setting also affects the 6581 at the same time?"

**Comment by drfiemost** [comment]
That doesn't look good indeed, the average one is far from the actual sampled waveform.
The reference data and tools are available here:
https://github.com/libsidplayfp/combined-waveforms/tree/master/new

> The only question is whether this setting also affects the 6581 at the same time?"

No, 6581 have completely different waveforms.

**Comment by acrouzet** [comment]
All the tunes I tested are volume-based.

**Comment by drfiemost** [comment]
The effect is audible with `/MUSICIANS/T/Toggle/Defier_of_Deadlines.sid`
Should get back at cw model again :/

**Comment by drfiemost** [comment]
Should be hopefully fixed in master, please test your favorite tunes

**Comment by acrouzet** [comment]
Seems fixed now.

**Comment by drfiemost** [comment]
Excellent, thanks!
Time for a bugfix release

**Comment by PM250B** [comment]
Cant test myself, yet. wating for next release.

**Comment by drfiemost** [comment]
Queued for next release in the following days.
Thanks!
