### ISSUE TITLE
PVS-Studio flagged: use ` = default;` syntax for body-removal in the `WaveformCalculator`

### ISSUE THREAD

**Issue by kcgen** [libsidplayfp/libsidplayfp#23]
Flagged in the `WaveformCalculator` class:

![2021-06-12_08-10](https://user-images.githubusercontent.com/1557255/121780560-c2746a00-cb55-11eb-8739-d1697dc5c22c.png)

Flagged in the `SID` class:

![2021-06-12_08-14](https://user-images.githubusercontent.com/1557255/121780681-4dedfb00-cb56-11eb-8b32-31922d064742.png)

**Reasoning**: https://pvs-studio.com/en/docs/warnings/v832/

**Comment by drfiemost** [comment]
Closed with #33
