### ISSUE TITLE
PVS-Studio flagged: shifting by 17 overflows `shift_register` in `WaveformGenerator::reset`

### ISSUE THREAD

**Issue by kcgen** [libsidplayfp/libsidplayfp#24]
Flagged in the `WaveformGenerator::reset()` function:

![2021-06-12_08-12](https://user-images.githubusercontent.com/1557255/121780626-14b58b00-cb56-11eb-912a-1d3809052fed.png)

**Reasoning**: https://pvs-studio.com/en/docs/warnings/v673/

**Comment by drfiemost** [comment]
Looks like a false positive, we're only interested in bit 22 so truncation is not an issue. Maybe an explicit cast would help?

**Comment by kcgen** [comment]
If we get the the 5th bit in `~shift-register` and then left-shift that by 17, then we stay in-bounds of the unsigned size -- and I think that's the same result?  

``` c++
(~shift_register & 1 << 5) << 17
```

**Comment by kcgen** [comment]
Wow - nice fix @drfiemost :-) 
As a casual reader, that is much easier to read too.

**Comment by drfiemost** [comment]
We already knew the value so no need to mess around, a comment explains what's going on.
