### ISSUE TITLE
PVS-Studio flagged: `EnvelopeGenerator` is missing constructor for `dac`

### ISSUE THREAD

**Issue by kcgen** [libsidplayfp/libsidplayfp#26]
Flagged in the `EnvelopeGenerator()` constructor:

![2021-06-12_08-19](https://user-images.githubusercontent.com/1557255/121780845-061ba380-cb57-11eb-9069-85c55e86c4b8.png)

**Reasoning**: https://pvs-studio.com/en/docs/warnings/v730/

**Comment by drfiemost** [comment]
Should be fixed now.
