### ISSUE TITLE
Coverity flagged: `firN / 2` loses fractional component in the `SincResampler` class

### ISSUE THREAD

**Issue by kcgen** [libsidplayfp/libsidplayfp#28]
Flagged in the `SincResampler::SincResample(...)` constructor:

![2021-06-12_08-25](https://user-images.githubusercontent.com/1557255/121781138-43346580-cb58-11eb-9e68-6ec831beea06.png)

**Reasoning**: https://pvs-studio.com/en/docs/warnings/v636/

---

I couldn't tell if the math of `firN / 2` is supposed to drop its fractional component or not. 

The implicit cast-to-double could be avoided if just the `firN / 2` portion was moved to it's own `const` variable, given `firN` isn't updated in these loops.  

If this were placed above the `for (int i = 0; i < firRES; i++)` loop, then it would only be calculated once instead of repeating it firRES * firN times.

Those are all the issues flagged by PVS Studio! That's not many, given the size of the code-base (and almost all just improvements as opposed to bug flags).  Nice work here! :+1:

**Comment by drfiemost** [comment]
I'm almost sure the value is supposed to be truncated. I've extracted the constant out of the loop for now but guess it's still flagged. Need to double check the Kaiser window formula and mark it as false positive in case.

**Comment by kcgen** [comment]
Confirmed fixed in the latest PVS Studio run (https://github.com/dosbox-staging/dosbox-staging/actions/runs/954723017). Thank you.

**Comment by kcgen** [comment]
@drfiemost , after merging this update to our main branch, Coverity flagged this change with:

``` text
>>>     CID 332414:  Incorrect expression  (UNINTENDED_INTEGER_DIVISION)
>>>     Dividing integer expressions "this->firN" and "2", and then converting the integer quotient to type "double". Any remainder, or fractional part of the quotient, is ignored.
335             const double firN_2 = static_cast<double>(firN / 2);
336     
337             for (int i = 0; i < firRES; i++)
338             {
339                 const double jPhase = (double) i / firRES + firN_2;
340     
```

**Comment by kcgen** [comment]
I suppose the cast to double is telling coverity we want a floating-point result, but inside the cast we're dropping the decimal part (that it thinks we'd like to retain). 

Given FirN is int, the 2 is int, I think we can store the result as int as well.. which should be pretty clear that we itend to perform integer-only math. 

The resuling int should be fine to use in the lower equations, because int can be added to double exactly without any loss of precision. 

This is just a hunch. I'm happy to try these outbefore hand and report back.  this is definitely an interesting chunk of math to the analyzers :-)

**Comment by kcgen** [comment]
![2021-06-23_18-16](https://user-images.githubusercontent.com/1557255/123187528-31539c00-d44f-11eb-8cd8-e95c82ec1ad7.png)

Sending a new scan request to Coverty that uses pure-`int`: `const int firN_2 = firN / 2;`.  Fingers crossed PVS is happy with this too.  Report back shortly.

**Comment by drfiemost** [comment]
Should be fixed now. Since we use the number as a double in the loop I've kept the conversion outside performed in two steps.
