### ISSUE TITLE
SidDatabase.cpp parseTime returns unusual results

### ISSUE THREAD

**Issue by KelticDanor** [libsidplayfp/libsidplayfp#32]
Just a very minor thing but after a few hundred checks this function starts misbehaving and returning corrupted data.

Specifically this loop seems to go past the bounds of the data causing corruption and depending on the corruption loops a long longer than one would expect. The function itself doesn't crash regardless of the corruption but the returned data is not what you would expect.
`    while (!isspace(*end))`
`    {`
`        end++;`
`    }`

I addressed it by just adding a length check though perhaps you'll have a more elegant way of addressing it.
`    while (!isspace(*end) && strlen(end) != 0)`
`    {`
`        end++;`
`    }`

And example before and after the call is as follows.
`String before call | 1:48`
`String after call |  EPPý6¹`

**Comment by drfiemost** [comment]
This would be more efficient:
```
    while ((*end != 0) && !isspace(*end))
    {
        end++;
    }
```

Can you please confirm it works for you?

**Comment by KelticDanor** [comment]
With that change I've tested with 54k files while logging the results and it looks like it works perfectly.

**Comment by drfiemost** [comment]
Excellent, thanks!
