### ISSUE TITLE
Emulation error?

### ISSUE THREAD

**Issue by pezz** [libsidplayfp/libsidplayfp#35]
Howdy,

I've noticed there's some pitch errors in Rob Hubbard's "Shockway Rider". You can hear it go a bit weird about 16 seconds into the tune.

Cheers.

**Comment by pezz** [comment]
Ah ok, just thought I'd ad the following.

DeepSID has HVSC 75 and plays it fine:
https://deepsid.chordian.net/?file=/MUSICIANS/H/Hubbard_Rob/Shockway_Rider.sid

Also according to the HVSC update text files Shockway Rider was updated in Update 63, and I know sidplayfp used to play it properly. I grabbed HVSC 62 from https://mirror.mos6581.de/hvsc/ and the version in that plays the same way.

**Comment by drfiemost** [comment]
In fact older versions are ok, I've tracked down the regression in 2.1.1, most likely due to the memory init pattern change.

**Comment by ian-coog** [comment]
Joxstrap/HVSC found the problem, memory $ed00-ed08 was not inited to 0, now the sid file is fixed for the next HVSC update.

**Comment by drfiemost** [comment]
Excellent, thanks!

**Comment by pezz** [comment]
Awesome, thanks to both of you, appreciate the effort.
