### ISSUE TITLE
Digiboost sticks when enabled

### ISSUE THREAD

**Issue by KelticDanor** [libsidplayfp/libsidplayfp#37]
Hey mate,

This has been discussed a little on the forum thread here: http://www.un4seen.com/forum/?topic=19493.msg136790#msg136790

The issue from what I understand is when digiboost is enabled it is not disabled again when playing 6581 sid tunes without reloading the engine. From the thread it appears Malade has addressed it but I think it would probably be good for the library to get a fix as well.

The examples used from the forum post are as follows:
Arkanoid.sid - 6581 tune
Galancy_Tune_00.sid - 8580 tune

1. When playing Arkanoid there is a drum affect is heard clearly when played first (2-3 seconds in)
2. Play Galancy_Tune_00, I don't think the tune matters, it is just to get the digiboost enabled.
3. Playing Arkanoid will have a very subdued drum affect compared to the first time

If you want me to test any fixes let me know and I'll give it a try. I've attached the [sidtunes.zip](https://github.com/libsidplayfp/libsidplayfp/files/7641346/sidtunes.zip) for reference.

**Comment by drfiemost** [comment]
Should be fixed by 8e49939, please check.

**Comment by KelticDanor** [comment]
I applied the change and it sounds like it has done the trick. I'll send a test plugin off for someone else with better ears but I think it is safe to say its fixed.

Thanks again!

**Comment by drfiemost** [comment]
Excellent, thanks!
