### ISSUE TITLE
Handful of warnings following FilterModelConfig refactoring

### ISSUE THREAD

**Issue by kcgen** [libsidplayfp/libsidplayfp#49]
![2022-02-15_00-17](https://user-images.githubusercontent.com/1557255/154020963-11544b3f-ed9d-4230-80d6-2fc8300ba734.png)

![2022-02-15_00-16_1](https://user-images.githubusercontent.com/1557255/154020967-d927bf97-1f57-40ea-81ae-e0d2d5b298f7.png)

![2022-02-15_00-16](https://user-images.githubusercontent.com/1557255/154020969-433470d2-ec34-4506-850a-ce6613f68f4f.png)

![2022-02-15_00-15](https://user-images.githubusercontent.com/1557255/154020970-c5904c05-aab1-4d4e-92d7-63bf9434fae9.png)

And a new warning from GCC 11 on Linux, MSYS2, and macOS:
``` 
FilterModelConfig.h:31:7:  warning [-Weffc++]: 
'class reSIDfp::FilterModelConfig' has pointer data members but does
not declare 'reSIDfp::FilterModelConfig(const reSIDfp::FilterModelConfig&)'
or 'operator=(const reSIDfp::FilterModelConfig&)'
```

Knocking out the assignment and copy operators should do the trick.
``` c++
MyClass (const MyClass&) = delete;
MyClass& operator= (const MyClass&) = delete;
```

**Comment by drfiemost** [comment]
Should be clean now
