### ISSUE TITLE
resid fails with assertion

### ISSUE THREAD

**Issue by mywave82** [libsidplayfp/libsidplayfp#50]
The lastest master of libresidplay 2e50ad50328fbf4cfbe7580a94cd9aea8355b2c0 and resid 17ca41aeddcfe4f132d6a5c3e99822778c188991 gives assertion if built with debugging

./configure --enable-debug

Seems that assertions is only evaluated if debug is enabled:

$gdb sidplay
(gdb) r "stop coder's naughtiness(tune 4).rsid"
**sidplayfp: src/builders/residfp-builder/residfp/FilterModelConfig.cpp:73: reSIDfp::FilterModelConfig::FilterModelConfig(double, double, double, double, double, double, const reSIDfp::Spline::Point*, int): Assertion `tmp > -0.5 && tmp < 65535.5' failed.**

Thread 1 "sidplayfp" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737314496256) at pthread_kill.c:44
44	pthread_kill.c: No such file or directory.
(gdb) bt
\#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737314496256) at pthread_kill.c:44
\#1  __pthread_kill_internal (signo=6, threadid=140737314496256) at pthread_kill.c:80
\#2  __GI___pthread_kill (threadid=140737314496256, signo=signo@entry=6) at pthread_kill.c:91
\#3  0x00007ffff64f8476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
\#4  0x00007ffff64de7b7 in __GI_abort () at abort.c:79
\#5  0x00007ffff64de6db in __assert_fail_base (fmt=0x7ffff6692770 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%\n", assertion=0x7ffff6acefc3 "tmp > -0.5 && tmp < 65535.5", file=0x7ffff6acef88 "src/builders/residfp-builder/residfp/FilterModelConfig.cpp", line=73, function=<optimized out>) at assert.c:92
\#6  0x00007ffff64efe26 in __GI___assert_fail (assertion=0x7ffff6acefc3 "tmp > -0.5 && tmp < 65535.5", file=0x7ffff6acef88 "src/builders/residfp-builder/residfp/FilterModelConfig.cpp", line=73, function=0x7ffff6acef00 "reSIDfp::FilterModelConfig::FilterModelConfig(double, double, double, double, double, double, const reSIDfp::Spline::Point*, int)") at assert.c:101
**\#7  0x00007ffff6aafc75 in reSIDfp::FilterModelConfig::FilterModelConfig (this=0x7ffff11aa010, vvr=1.5, vdv=5.0750000000000002, c=4.7000000000000003e-10, vdd=12.18, vth=1.3100000000000001, 
    ucox=2.0000000000000002e-05, opamp_voltage=0x7ffff6acf1c0 <reSIDfp::opamp_voltage>, opamp_size=33) at src/builders/residfp-builder/residfp/FilterModelConfig.cpp:73**
\#8  0x00007ffff6ab097d in reSIDfp::FilterModelConfig6581::FilterModelConfig6581 (this=0x7ffff11aa010) at src/builders/residfp-builder/residfp/FilterModelConfig6581.cpp:118
\#9  0x00007ffff6ab08a7 in reSIDfp::FilterModelConfig6581::getInstance () at src/builders/residfp-builder/residfp/FilterModelConfig6581.cpp:97
\#10 0x00007ffff6ab5653 in reSIDfp::Filter6581::Filter6581 (this=0x5555555947f0) at src/builders/residfp-builder/residfp/Filter6581.h:358
\#11 0x00007ffff6ab3a02 in reSIDfp::SID::SID (this=0x5555555a3dd0) at src/builders/residfp-builder/residfp/SID.cpp:136
\#12 0x00007ffff6aabda1 in libsidplayfp::ReSIDfp::ReSIDfp (this=0x555555593040, builder=0x555555594880) at src/builders/residfp-builder/residfp-emu.cpp:61
\#13 0x00007ffff6aaabb6 in ReSIDfpBuilder::create (this=0x555555594880, sids=3) at src/builders/residfp-builder/residfp-builder.cpp:50
\#14 0x00005555555662b9 in ConsolePlayer::createSidEmu (this=0x7fffffffdaa0, emu=EMU_RESIDFP) at src/player.cpp:441
\#15 0x00005555555666f3 in ConsolePlayer::open (this=0x7fffffffdaa0) at src/player.cpp:563
\#16 0x0000555555561876 in main (argc=2, argv=0x7fffffffdec8) at src/main.cpp:53
(gdb) up
\#1  __pthread_kill_internal (signo=6, threadid=140737314496256) at pthread_kill.c:80
80	in pthread_kill.c
(gdb) up
\#2  __GI___pthread_kill (threadid=140737314496256, signo=signo@entry=6) at pthread_kill.c:91
91	in pthread_kill.c
(gdb) up
\#3  0x00007ffff64f8476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
26	../sysdeps/posix/raise.c: No such file or directory.
(gdb) up
\#4  0x00007ffff64de7b7 in __GI_abort () at abort.c:79
79	abort.c: No such file or directory.
(gdb) up
\#5  0x00007ffff64de6db in __assert_fail_base (fmt=0x7ffff6692770 "%%s%%s%%s:%%u: %%s%%sAssertion ``%%s' failed.\n%%n", assertion=0x7ffff6acefc3 "tmp > -0.5 && tmp < 65535.5", 
    file=0x7ffff6acef88 "src/builders/residfp-builder/residfp/FilterModelConfig.cpp", line=73, function=<optimized out>) at assert.c:92
92	assert.c: No such file or directory.
(gdb) up
\#6  0x00007ffff64efe26 in __GI___assert_fail (assertion=0x7ffff6acefc3 "tmp > -0.5 && tmp < 65535.5", file=0x7ffff6acef88 "src/builders/residfp-builder/residfp/FilterModelConfig.cpp", line=73, 
    function=0x7ffff6acef00 "reSIDfp::FilterModelConfig::FilterModelConfig(double, double, double, double, double, double, const reSIDfp::Spline::Point*, int)") at assert.c:101
101	in assert.c
(gdb) up
**\#7  0x00007ffff6aafc75 in reSIDfp::FilterModelConfig::FilterModelConfig (this=0x7ffff11aa010, vvr=1.5, vdv=5.0750000000000002, c=4.7000000000000003e-10, vdd=12.18, vth=1.3100000000000001, 
    ucox=2.0000000000000002e-05, opamp_voltage=0x7ffff6acf1c0 <reSIDfp::opamp_voltage>, opamp_size=33) at src/builders/residfp-builder/residfp/FilterModelConfig.cpp:73
73	        assert(tmp > -0.5 && tmp < 65535.5);**
(gdb) l
68	
69	    for (int x = 0; x < (1 << 16); x++)
70	    {
71	        const Spline::Point out = s.evaluate(x);
72	        double tmp = out.x;
**73	        assert(tmp > -0.5 && tmp < 65535.5);**
74	        opamp_rev[x] = static_cast<unsigned short>(tmp + 0.5);
75	    }
76	}
77	
(gdb) p s.evaluate(0)
$6 = {x = -3595.1967285815922, y = 1.9344740180963929}

**Comment by drfiemost** [comment]
Thanks for checking, in fact for the 6581 the first values are negative and should be forced to zero.
