### ISSUE TITLE
Crash when requesting an odd number of samples for stereo output

### ISSUE THREAD

**Issue by reFX-Mike** [libsidplayfp/libsidplayfp#57]
I'm stuck. Can somebody post the most simple example that renders into a stereo buffer?

I've started my own version of a SID player (yet another one), because I have some (IMO) neat ideas. I can play any .sid file I like as long as I stick to mono. As soon as I change the config to two channels, the "engine.play" call crashes in the mixer. I provide a MUCH larger buffer than needed (65536 int16), and only request 441 output samples. So even if the stereo mode returns 882 shorts instead of 441, there is still plenty of room.

I use clang 15.0.5 on Windows. The executable I'm building is 64-bit.

Here is some code, that is normally in a class, but I've pasted it here in case somebody can spot something dodgy:

```
void main ()
{
	ReSIDfpBuilder	residfp { "residfp" };
	sidplayfp	engine;
	SidTune		tune { nullptr };
	SidConfig	config;

	config.sidEmulation = &residfp;
	tune.load ( "Hard_Re_Start_2SID.sid" );
	tune.selectSong ( 0 );

	auto	info = tune.getInfo ();
	residfp.remove ();
	residfp.create ( info->sidChips () );

	config.frequency = 44100;
//	config.playback = SidConfig::playback_t::STEREO;    // If I uncomment this line, it crashes in the while loop further down
	engine.config ( config );
	engine.fastForward ( 100 );
	engine.load ( &tune );

	int16_t		outBuffer[ 65536 ];

        while ( 1 )
	     engine.play ( outBuffer, 441 );
}
```
Also, if the output is supposed to be stereo, are the int16 just interleaved? Do I then get twice as many int16 than I request?

Please help me.

**Comment by reFX-Mike** [comment]
I should note that I'm aware that I can copy the left into the right buffer, but the goal here is to play back SID files that use more than one SID chip and retain their stereo image. That's why I picked "Hard(Re)start_2SID" as the example.

**Comment by drfiemost** [comment]
The requested size is too small, the engine is unable to provide so few bytes, not sure exactly why though. Try with 32768, it works. You may also want to set the second SID address:

`config.secondSidAddress = 0xd420;`

**Comment by reFX-Mike** [comment]
A good night's sleep helps. The problem is quite simple: for a stereo signal, the number of samples requested has to be even, which makes sense since the call generates an interleaved signal, so saying, "I want 220 values for the left and 221 for the right," doesn't make any sense.

So in stereo mode, I've modified the play call to multiply by two and then de-interlave after (my audio buffers are two separate float mono channels). Now it works perfectly without further modification.

I don't think the size matters, only that it has to be even for stereo output. Maybe a few asserts would help?

Do I have to manually specify the second (and third) SID addresses? Doesn't the TuneInfo contain that kind of information? Doesn't it depend on where the *.sid expects the second (and third) SID chips will be?

**Comment by drfiemost** [comment]
Ahhh, I should definitely add a check for buffer size, crashing is not an option.

As for sid (and mus) tunes you're right, the extra SID addresses are autodetected.

**Comment by reFX-Mike** [comment]
I've also noticed some unused variables, which hinder me from compiling with warnings-are-errors. Would you like me to open a pull request for that?

**Comment by drfiemost** [comment]
Sure, if you have a fix feel free to send a PR

**Comment by drfiemost** [comment]
Please leave this open until the issue is fixed. I've also noticed a systematic crash with small count sizes.

**Comment by reFX-Mike** [comment]
The most straightforward remedy would be an internal buffer that captures the extra output and feeds it back on the next play call.
