### ISSUE TITLE
Unused variable warnings

### ISSUE THREAD

**Issue by reFX-Mike** [libsidplayfp/libsidplayfp#58]
Should the unused variables needed for debugging be marked ```[[ maybe_unused ]]``` instead of using a compiler-specific extension, or is it critical that libsidplayfp compiles with older compilers?

Same question for ```[[ deprecated ]]``` and ```[[ nodiscard ]]```

**Comment by drfiemost** [comment]
At the moment we are still maintaining compatibility with pre c++11 compilers.
There are the SID_DEPRECATED and SID_UNUSED macros available from siddefs.h

**Comment by reFX-Mike** [comment]
They are already used, but they only work with GCC. Maybe it would be a good idea to use something like

https://nemequ.github.io/hedley/

It's a single header file, and then libsidplayfp could become a zero-configuration library!

It strangely doesn't feature a HEDLEY_UNUSED macro, but they recommend to simply cast potentially unused variables to ```(void)```. Compilers then see that variable as "used", but its a no-op.

**Comment by reFX-Mike** [comment]
Are there any strong reasons to hold libsidplayfp back to pre-c++11 compilers? Even for embedded platforms, much newer compilers are readily and freely available, so I have a bit of trouble understanding why to hold back.

When we modernized our large codebase to use C++11/14/17/20 features, the code became easier to read, became faster in places, and we discovered a lot of previously unknown bugs.

Maybe a poll of existing clients can be performed to find any blocks to modernization?

**Comment by drfiemost** [comment]
it's mostly due to laziness/lack of time. I have some plans for switching to a modern standard in version 3.0 but no established timeline.

**Comment by reFX-Mike** [comment]
I would love to help with this. I like refactoring and modernizing old code. What is the C++ standard you would be comfortable with upgrading to? C++17 or even 20?

**Comment by drfiemost** [comment]
I think C++17 is well supported nowadays and could be a good choice. However I'd like to keep public headers compatible with older standards as much as possible.

**Comment by reFX-Mike** [comment]
How would that work? What do you mean by "as much as possible"? Either we can use the new features like ```[[ nodiscard ]]```, ```[[ deprecated ]]``` or we can't. If we can't, then what's the point of modernization? So we can update to C++17, but not really?

**Comment by emoon** [comment]
I assume the point is that you can use C++17 features inside the cpp files, but leave the (public) headers free of those features.

**Comment by drfiemost** [comment]
Exactly that. If anything one could use the __cplusplus macro to test for supported standards but without forcing the apps that use the library to adopt a minimum c++ version.

**Comment by reFX-Mike** [comment]
In that case, I would only replace a few UNUSED macros with [[ maybe_unused ]] and call it a day. It solves my immediate problem without investing too much time.

I will create a pull request in the next few days.
