### ISSUE TITLE
GPLv3

### ISSUE THREAD

**Issue by reFX-Mike** [libsidplayfp/libsidplayfp#59]
Can this project be dual-licensed under GPLv2 and GPLv3? So the user can choose but is not limited to GPLv2-related code?

I'm writing yet another SID player that uses JUCE (GPLv3) for the UI, and I would also like to add some user-adjustable FX to the output. The reverb I'm planning to use is licensed under GPLv3, JUCE uses GPLv3, so I need to license my project as GPLv3, but apparently, that is incompatible with GPLv2. I'm not quite sure how it all works. This is my first GPL-licensed project.

**Comment by drfiemost** [comment]
The README file says:

> This program is free software; you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation; either version 2 of the License, **or
> (at your option) any later version.**

so there should be no problem.

Also please use the discussion section for questions.
