### ISSUE TITLE
2.1.0 compilation error in bundled exSID (thread implementation related)

### ISSUE THREAD

**Issue by samoht0** [libsidplayfp/libsidplayfp#6]
I'm getting
```
src/builders/exsid-builder/driver/exSID.c:42:12: fatal error: c11threads.h: No such file or directory
   42 |   #include "c11threads.h"
```
when compiling 2.1.0. My understanding is, the wrong thread implementation is chosen. exSID.c includes <threads.h> or "c11threads.h" as before. Maybe caused by changes in configure:

2.0.5
_checking threads.h usability... yes_
_checking threads.h presence... yes_
_checking for threads.h... yes_
checking for library containing pthread_create... -lpthread

2.1.0 (no threads.h detection)
checking whether pthreads work with "-pthread" and "-lpthread"... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes

Or is there any configure option to control the behaviour?

**Comment by samoht0** [comment]
OK, there's another reason.
c11threads.h is not included in src/builders/exsid-builder/driver/ in 2.1.0...

**Comment by drfiemost** [comment]
The tarball is broken, will reupload later. Sorry for the inconvenience.

**Comment by samoht0** [comment]
> The tarball is broken, will reupload later. Sorry for the inconvenience.

Thanks. Will test when new tarball is up.

**Comment by drfiemost** [comment]
Reuploaded, the correct one has the following md5sum:
d06ba6a9f407ebdb75125b53dc61bbad  libsidplayfp-2.1.0.tar.gz

Thanks for reporting!
