### ISSUE TITLE
Rob Hubbard/Last V8 plays at unlimited speed

### ISSUE THREAD

**Issue by reFX-Mike** [libsidplayfp/libsidplayfp#60]
This library and the command-line tool play the whole song within a few seconds, but it should last over two minutes. It's an RSID, not a typical PSID. Is there a problem with RSID playback?

**Comment by drfiemost** [comment]
Plays fine here, make sure you have loaded the kernal rom.

**Comment by reFX-Mike** [comment]
Is it legal to ship these binaries with my player or do I have to rely on the user to supply these?

**Comment by drfiemost** [comment]
I cannot give any legal advice. To be on the safe side I prefer leaving them out and plenty of tunes still works ok, VICE (and other emulators too) on the other side include them in the package. I don't think anyoune would claim any rights on decades old firmware, at least for free/OS software, but it's still a gray area nonetheless.

**Comment by reFX-Mike** [comment]
Thank you. The tune plays correctly now.
