### ISSUE TITLE
Incorrect sample playback in violator.sid (HVSC) song 4

### ISSUE THREAD

**Issue by mbwum73** [libsidplayfp/libsidplayfp#65]
I noticed a weird issue with sample playback.
To hear the problem go to the HVSC (I used version 78). 
There play the following file: \GAMES\S-Z\Violater.sid

This tune has 4 songs. Song 4 has an issue with sample playback. Somehow the bass drum sample sounds very high pitched or it's not reading the sample at al causing a werid sound. This is wrong. I tried the file on a real c64 with a real sid and it plays fine. So I think it's caused by libsidplayfp.

**Comment by drfiemost** [comment]
It plays fine with vsid too. Have you tried with older version?

**Comment by drfiemost** [comment]
It broke with 3a970a77bebbb530125cb12d2359e355c67ac8e6, guess it's using an uninitialized memory location. Will report it to the HVSC crew.

**Comment by mbwum73** [comment]
Thank you for figuring it out. Good to know it's not caused by libsidplayfp.


________________________________
Van: Leandro Nini ***@***.***>
Verzonden: woensdag 11 januari 2023 09:28
Aan: libsidplayfp/libsidplayfp ***@***.***>
CC: mbwum73 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [libsidplayfp/libsidplayfp] Incorrect sample playback in violator.sid (HVSC) song 4 (Issue #65)


It broke with 3a970a7<https://github.com/libsidplayfp/libsidplayfp/commit/3a970a77bebbb530125cb12d2359e355c67ac8e6>, guess it's using an uninitialized memory location. Will report it to the HVSC crew.

**Comment by drfiemost** [comment]
Confirmed by the HVSC guys, here's the fixed one that will be included in #79
[Violator.zip](https://github.com/libsidplayfp/libsidplayfp/files/10433563/Violator.zip)

Thanks for reporting!

**Comment by mbwum73** [comment]
Thank you very much.
________________________________
Van: Leandro Nini ***@***.***>
Verzonden: dinsdag 17 januari 2023 10:49
Aan: libsidplayfp/libsidplayfp ***@***.***>
CC: mbwum73 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [libsidplayfp/libsidplayfp] Incorrect sample playback in violator.sid (HVSC) song 4 (Issue #65)


Confirmed by the HVSC guys, here's the fixed one that will be included in #79
Violator.zip<https://github.com/libsidplayfp/libsidplayfp/files/10433563/Violator.zip>

Thanks for reporting!
