### ISSUE TITLE
Weird high pitch note in Arkanoid (alternative drums) tune

### ISSUE THREAD

**Issue by mbwum73** [libsidplayfp/libsidplayfp#66]
I'm not sure this is a bug or a bad ripped tune.
There might be a little problem with Arkanoid (Alternative Drums). When I play the main tune around 00:52 you will hear a high pitch sound. It can also be heared at 01:02, 1:43 and 1:53. It's just a high pitch tone that imho should not be there. It's not a sample and it's not rhytmic. It's a glitch in the tune.
Because this version of arkanoid never appeared in a game I cannot compare it. May be normal behaviour or a bad dump?

I also tried playing it on my android phone with a program called droidsound-e.
In that program I can choose two options to play sid (they call it the builder mode).
If I choose residfpbuider the weird high pitch glitcy notes are there. When I choose ReSIDBuilder however I do not hear the weird glitch. So that assumes the dump is okay, but I'm not sure. I hope you can at least confirm you also hear the weird glitch.
When I choose a 8550 sid model I also hear the glitch and just as loud as on a 6581. So I don't think it's a bad sample, because I would hear it on a much lower volume on a 8550.

When playing the normal Arkanoid version (so not with the alternative drums) I cannot hear the glitch.

**Comment by drfiemost** [comment]
Confirmed, it started in 2.0.2. It happens with both resid and residfp.
Will bisect to find the offending commit.

**Comment by drfiemost** [comment]
The commit is dfd46bd4b0461ad62b9caa4dfa54a9dcdd269163, which was intended to fix /MUSICIANS/G/Galway_Martin/Wizball.sid by changing the default filter setting.
The problem is that 6581 chips have extremely variable filter so yes, it can happen on a real SID too.
Not sure if I should revert the change, leave it as is or finding a value that makes both tunes sound ok...

**Comment by mbwum73** [comment]
Finding a value that make both sids sound good would  IMHO be the best solution. But why doesn't this glitch appear on the normal arkanoid version? Same sid, only different samples. Or do the samples use the filter in a different way?
________________________________
Van: Leandro Nini ***@***.***>
Verzonden: dinsdag 24 januari 2023 18:06
Aan: libsidplayfp/libsidplayfp ***@***.***>
CC: mbwum73 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [libsidplayfp/libsidplayfp] Weird high pitch note in Arkanoid (alternative drums) tune (Issue #66)


The commit is dfd46bd<https://github.com/libsidplayfp/libsidplayfp/commit/dfd46bd4b0461ad62b9caa4dfa54a9dcdd269163>, which was intended to fix /MUSICIANS/G/Galway_Martin/Wizball.sid by changing the default filter setting.
The problem is that 6581 chips have extremely variable filter so yes, it can happen on a real SID too.
Not sure if I should revert the change, leave it as is or finding a value that makes both tunes sound ok...

**Comment by drfiemost** [comment]
For the record, on a real 6581 marked 3884 the glitch on Arkanoid is present but there's no octave drop in Wizball.
Will test a couple more chips later on.

**Comment by acrouzet** [comment]
The high pitched note is just a glitch with the song itself, not the filter. Disabling the filter makes this evident. Making the filter dark enough will hide this glitch, but I don't think the note being audible is evidence of an issue with the filter emulation. Maybe try  playing this song on real hardware with the filter disabled to see if this is a problem with the emulation or the .sid rip.

**Comment by drfiemost** [comment]
Aahhh, in fact there is a high pitched note in channel 3:

```
|  2600 | 08A8 (+ 0014) .. .... 936 | 1A2C  G-4 B7  41 .... ... | ....  ... ..  .. .... ... | 71C0 .. ... . |
|  2601 | 08BC (+ 0014) .. .... 940 | ....  ... ..  .. .... ... | ....  ... ..  .. .... ... | 6C20 .. ... . |
|  2602 | 08D0 (+ 0014) .. .... 94A | ....  ... ..  .. .... ... | 0019 (+ 0019) .. .... ... | 6680 .. ... . |
|  2603 | 08E4 (+ 0014) .. .... 954 | ....  ... ..  .. .... ... | 0032 (+ 0019) .. .... 614 | 60E0 .. ... . |
|  2604 | 08F8 (C#3 A5) .. .... 95E | ....  ... ..  40 .... ... | 0019 (- 0019) .. .... 628 | 5B40 .. ... . |
|  2605 | 08E4 (C-3 A4) .. .... 968 | ....  ... ..  .. .... ... | 0000 (- 0019) .. .... 63C | 55A0 .. ... . |
|  2606 | 08D0 (- 0014) .. .... 972 | ....  ... ..  .. .... ... | FFE7 (B-7 DF) .. .... ... | 5000 .. ... . |
|  2607 | 08BC (- 0014) .. .... 97C | ....  ... ..  .. .... ... | FFCE (- 0019) .. .... 650 | 4A60 .. ... . |
|  2608 | 08A8 (- 0014) .. .... 986 | 45DE  C-6 C8  41 .... ... | 08BC (C-3 A4) .. .... 614 | 29C0 .. ... . |
|  2609 | 0894 (- 0014) .. .... 990 | ....  ... ..  .. .... ... | ....  ... ..  .. .... 628 | 5360 .. ... . |
```

So I guess this tune is intended for a chip with dark filter.

BTW for future reference the HVSC path is `/MUSICIANS/G/Galway_Martin/Arkanoid_alternative_drums.sid` so I don't have to look it up again  :)
