### ISSUE TITLE
Unused variables, parameters, and class-members

### ISSUE THREAD

**Issue by reFX-Mike** [libsidplayfp/libsidplayfp#68]
When using the clang option to turn warnings into errors, it becomes impossible to compile libsidplay. Using clang 15.0.7 (latest):

```src/sidemu.h``` line 127 and 128. All four parameters are never used for anything. The current macro that goes behind them doesn't do anything except maybe for GCC users.

```src/Event.h``` line 50. The parameter ```const char * const m_name``` is not used. The compiler deducts that the value is only set in the public constructor but never used anywhere else again, so it gets optimized away, making the value useless. Maybe add a getter for it?

**Comment by drfiemost** [comment]
Clang should support \_\_attribute\_\_ ((unused)), it can be enabled in siddefs.h
Also we might use the new maybe_unused when in c++17 mode. Something like this should do:

```
/* Unused attributes */
#if __cplusplus >= 201703L
#  define SID_UNUSED [[maybe_unused]]
#elif defined(__GNUC__) || defined(__clang__)
#  define SID_UNUSED __attribute__ ((unused))
#else
#  define SID_UNUSED
#endif
```

As for the unused private member it can't be marked as unused since gcc would complain, adding a getter could be a good workaround.

**Comment by reFX-Mike** [comment]
That wouldn't help MSVC users. I really really don't understand the resistance to simply adding ```[[ maybe_unused ]]``` directly instead of using macros and vendor-specific attributes. This is 2023, not 1998. The number of clients consuming this library is tiny. I would simply make the change, and if there is significant pushback, you can still revert it. I guarantee you; nothing will happen. Nobody will complain.
