### ISSUE TITLE
'strnicmp' is deprecated. Use ISO C and C++ conformant name: _strnicmp

### ISSUE THREAD

**Issue by reFX-Mike** [libsidplayfp/libsidplayfp#69]
In the file ```src/stringutils.h``` in line 69 and 99, you use ```strnicmp```. Please replace with ```_strnicmp```

**Comment by reFX-Mike** [comment]
It may be easiest to remove the #ifdef checks altogether and always use the provided function. Why bother having three different code paths if one is tested, works, and does what is needed? We could avoid another configuration step, moving this library closer to being used without any configuration.

It would also simplify any unit tests. I'm not sure these functions are even tested right now.

**Comment by mywave82** [comment]
strncasecmp() is part of the POSIX standard; so probably makes more sense to use that and fallback to strnicmp() in windows if its present is is not detected.

**Comment by drfiemost** [comment]
The Microsoft docs confirm this:
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strnicmp-wcsnicmp?view=msvc-170

stricmp is deprecated too
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/stricmp-wcsicmp?view=msvc-170
