### ISSUE TITLE
UB in utils/MD5/MD5.cpp line 193

### ISSUE THREAD

**Issue by reFX-Mike** [libsidplayfp/libsidplayfp#70]
In ```utils/MD5/MD5.cpp``` on line ```193```, you subtract from a pointer. The exact clang error message is:

```error : performing pointer subtraction with a null pointer may have undefined behavior```

A simple fix is to cast the pointer to uintptr_t instead of subtracting a nullptr.

**Comment by drfiemost** [comment]
Can you submit a pull request?

**Comment by reFX-Mike** [comment]
Unfortunately, no, but here is line 193 changed to do the exact same thing, but without the UB

```if ((((uintptr_t)data) & 3) == 0)```
