### ISSUE TITLE
Faster seeking bar via GPU?

### ISSUE THREAD

**Issue by rayman3003** [libsidplayfp/libsidplayfp#74]
Is it possible to add GPU utilization (by adding Cuda or GPGPU features), to speed-up the seeking bar progress of libsidplayfp?

https://en.wikipedia.org/wiki/CUDA

https://en.wikipedia.org/wiki/General-purpose_computing_on_graphics_processing_units

**Comment by mywave82** [comment]
libsidplayfp does per-cycle emulating of a C64, so most operations performed are serialized and depend on the exit-status of the previous operation. It could perhaps benefit of using a separate thread for synthesize of audio.

CUDA makes most sense if you have repeating parallell tasks, and would also require a complete re-implementation which is probably beyond the scope of what the current maintainers are willing to use time on.

**Comment by drfiemost** [comment]
As said above multi-threading could help with performance but would require significant re-engineering of the code.

Also seeking is a client-side feature; a player could pre-render the wav in a separate thread and then seeking would be as fast as any streaming format. This is really out of the scope for this project.

As a side note I'm toying with the idea of using openMP to speed up the initialization code.
