### ISSUE TITLE
Low audio volume in general

### ISSUE THREAD

**Issue by bytespiller** [libsidplayfp/libsidplayfp#79]
The loudness of the libsidplayfp output is a bit lower than normal, no matter the SID model. I regularly have to up my volume when listening to SID tunes and lower it back down for anything else.

I've measured it in the Audacity and it seems that at maximum the audio level reaches around the -10db below the reference (if I'm reading this correctly). I've selected SID 6581 when testing since its output is louder.

**Comment by drfiemost** [comment]
It should be better now in 2.6
