### ISSUE TITLE
No sound in part of \MUSICIANS\H\Honey\Experiment_2-Thema.sid

### ISSUE THREAD

**Issue by drfiemost** [libsidplayfp/libsidplayfp#81]
> \MUSICIANS\H\Honey\Experiment_2-Thema.sid
> sidplayfp-2.5.0 doesnt play sound in 1:52-2:09 but there is a faint sound in the SOASC= recording from the C64:
> http://gemmei.ftp.acc.umu.se/mirror/media/Oakvalley/soasc/hvsc/075/MP3/MUSICIANS/H/Honey/Experiment_2-Thema_T001.sid_CSG8580R5.mp3

reported by efy

**Comment by drfiemost** [comment]
Checked the sid dump but still haven't figured out what causes the volume drop here. It's not the filter, it happens even when it's disabled, nor the global volume.

**Comment by reFX-Mike** [comment]
That's oscillator leakage in action. If you change this:

```
	// DAC leakage
	if ( ! input )
		return dac[ 0 ] / 2.0;
```

to this

```
	// DAC leakage
	if ( ! input )
		return dac[ 0 ] * 2.0;
```

It will sound very similar to the mp3.

**Comment by drfiemost** [comment]
Good! So we have a test tune and this can be handled with #102

I'm working on a better implementation where each open transistor contributes a small fraction of the current it lets through when closed. Then we can use this tune to estimate the leakage factor.

**Comment by drfiemost** [comment]
So this is finally fixed with https://github.com/libsidplayfp/libsidplayfp/commit/dd023497d61571ca68980fff5143751fa563d741  🎉​
