### ISSUE TITLE
Popping artifacts while the SID voices are muted

### ISSUE THREAD

**Issue by bytespiller** [libsidplayfp/libsidplayfp#83]
I've noticed repeated popping while the SID voices are muted.

For example in the song `/MUSICIANS/F/Fegolhuzz/Vi_drar_till_fjaellen.sid` after the **0:10** a rhythmical popping can be heard while all the SID voices are muted.

It seems to me that the popping might be related to the voice 1 (it seems it follows its rhythm?). If you enable only the voice 2 and/or the voice 3 you can still hear the rhythmical popping, but it is of course easier to perceive it when all the voices are muted.

I've tried with some much older version of the lib and the phenomenon is still present there, so it's not a new v2.5.0 thing. Happens for both SID models.

Example to reproduce the issue: `sidplayfp.exe -b10 -u1 -u2 -u3 Vi_drar_till_fjaellen.sid`

**Comment by drfiemost** [comment]
It's caused by the writes to $d418 which change the filter type and there's not much we can do about it. Happens on real hardware too.

[Vi_drar_till_fjaellen dump](https://github.com/libsidplayfp/libsidplayfp/files/12261042/Vi_drar_till_fjaellen.txt)
