### ISSUE TITLE
build issues with macOS

### ISSUE THREAD

**Issue by Alexco500** [libsidplayfp/libsidplayfp#87]
During build, sidplayer1.bin and sidplayer2.bin are created with some shell od & sed things. The od provided by macos is BSD style only and does not support -w argument. Solution to this is to use the Linux coreutils package with macports, which will make the GNU od available as god. The Makefile checks this and tries to use "god" directly, but the build fails silently if

- god is not available, shell bails out with unknown command, but sidplayer1.bin and sidplayer2.bin are created with zero length. Build process continues without issues, but resulting lib is not working correctly
- sidplayer1.bin and/or sidplayer2.bin already existing with zero length, they won't be recreated (shell script will again fail silently during build...)

Shell part working correctly:
>o65file=`echo src/sidtune/sidplayer1.bin | sed 's/bin/o65/'`;\
	xa -R -G src/sidtune/sidplayer1.a65 -o $o65file &&\
	god -v -An -w8 -tx1 $o65file | sed -re 's/[[:alnum:]]+/0x&,/g' > src/sidtune/sidplayer1.bin &&\
	rm -f $o65file
o65file=`echo src/sidtune/sidplayer2.bin | sed 's/bin/o65/'`;\
	xa -R -G src/sidtune/sidplayer2.a65 -o $o65file &&\
	god -v -An -w8 -tx1 $o65file | sed -re 's/[[:alnum:]]+/0x&,/g' > src/sidtune/sidplayer2.bin &&\
	rm -f $o65file

Shell fails due to wrong od and continues:
>alexc@Narya:[libsidplayfp] make
o65file=`echo src/sidtune/sidplayer1.bin | sed 's/bin/o65/'`;\
	xa -R -G src/sidtune/sidplayer1.a65 -o $o65file &&\
	od -v -An -w8 -tx1 $o65file | sed -re 's/[[:alnum:]]+/0x&,/g' > src/sidtune/sidplayer1.bin &&\
	rm -f $o65file
od: illegal option -- w
usage: od [-aBbcDdeFfHhIiLlOosvXx] [-A base] [-j skip] [-N length] [-t type]
          [[+]offset[.][Bb]] [file ...]
o65file=`echo src/sidtune/sidplayer2.bin | sed 's/bin/o65/'`;\
	xa -R -G src/sidtune/sidplayer2.a65 -o $o65file &&\
	od -v -An -w8 -tx1 $o65file | sed -re 's/[[:alnum:]]+/0x&,/g' > src/sidtune/sidplayer2.bin &&\
	rm -f $o65file
od: illegal option -- w
usage: od [-aBbcDdeFfHhIiLlOosvXx] [-A base] [-j skip] [-N length] [-t type]
          [[+]offset[.][Bb]] [file ...]
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in tests
make[2]: Nothing to be done for `all'.
/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -std=c++17 -DHAVE_CONFIG_H -I. -I./src  -I/opt/local/include -I ./src/builders/residfp-builder -I ./src/builders/residfp-builder/residfp -I ./src/builders/resid-builder -I ./src/builders/resid-builder/resid -I ./src -I ./src/sidtune -I ./src   -pthread -I/opt/local/include/libftdi1 -I/opt/local/include/libusb-1.0 -DNDEBUG  -fvisibility=hidden -fvisibility-inlines-hidden  -I/opt/local/includec -MT src/libsidplayfp_la-EventScheduler.lo -MD -MP -MF src/.deps/libsidplayfp_la-EventScheduler.Tpo -c -o src/libsidplayfp_la-EventScheduler.lo `test -f 'src/EventScheduler.cpp' || echo './'`src/EventScheduler.cpp

**Comment by mywave82** [comment]
This sounds like something that should be tested for in configure.ac instead of the very simple logic that is in Makefile.am today

```
if MACOS
  OD = god
else
  OD = od
endif
```

**Comment by drfiemost** [comment]
We can add a check like this in configure.ac
`AC_CHECK_PROGS ([OD], [god od])`
then force the Makefile to fail if $OD is empty.

Similar check would be required for `xa` too.

**Comment by drfiemost** [comment]
@Alexco500 please check if #88 works for you

**Comment by Alexco500** [comment]
Not completely. Configure is now checking that:
> checking for god... no
checking for od... od

But it does not throw an error for macOS, if god is not found. I can still build a broken library.

**Comment by drfiemost** [comment]
Ah, right! Changed to check if od (or god) actually supports the -w flag.

**Comment by Alexco500** [comment]
Now configure complains about -w, but continues until the end.
>checking for od that supports -w... /usr/bin/od: illegal option -- w
usage: od [-aBbcDdeFfHhIiLlOosvXx] [-A base] [-j skip] [-N length] [-t type]
          [[+]offset[.][Bb]] [file ...]

>checking for debugging... Build without debugging messages

but make will now stop directly
>resid/wave8580__ST.dat src/builders/resid-builder/resid/wave8580__ST.h
[ -n "" ] || { echo "od not found"; false; } && \
	o65file=`echo src/sidtune/sidplayer1.bin | sed 's/bin/o65/'`;\
	xa -R -G src/sidtune/sidplayer1.a65 -o $o65file &&\
	 -v -An -w8 -tx1 $o65file | sed -re 's/[[:alnum:]]+/0x&,/g' > src/sidtune/sidplayer1.bin &&\
	rm -f $o65file
od not found
-o requires an argument
make: *** [src/sidtune/sidplayer1.bin] Error 1

**Comment by drfiemost** [comment]
Cleaned up and added a check for xa. Should be ok now.
