### ISSUE TITLE
Replace OpenMP with c++11 threads for building the filter tables

### ISSUE THREAD

**Issue by drfiemost** [libsidplayfp/libsidplayfp#92]
BTW, one thing you could cherry-pick immediately would be my removal of OpenMP with std::thread. The startup time for both filter configs has been lowered from 300ms to 100ms (on my machine, in release mode). No defines needed, no compiler switches, no config file. It's a C++11 standard feature.

_Originally posted by @reFX-Mike in https://github.com/libsidplayfp/libsidplayfp/discussions/89#discussioncomment-7373524_

**Comment by drfiemost** [comment]
https://github.com/reFX/libsidplayfp/blob/2fc0767744f5a2a8f14904e19b117f29366724e5/src/sidplayfp/residfp/FilterModelConfig6581.cpp#L260-L272

**Comment by reFX-Mike** [comment]
Now that you’ve officially adopted C++11 as a requirement, this can be implemented easily.

**Comment by drfiemost** [comment]
Queued for next release

**Comment by reFX-Mike** [comment]
Looks good. Did you do a performance comparison? I’m just curious.
