### ISSUE TITLE
Improve combined waveforms model

### ISSUE THREAD

**Issue by drfiemost** [libsidplayfp/libsidplayfp#97]
Use the new 6581 samplings to calculate the combined waveforms parameters (see https://github.com/libsidplayfp/combined-waveforms/tree/master/new)
Also evaluate the reintroduction of the `topbit` parameter in the model.

**Comment by reFX-Mike** [comment]
Would it help if I run that program on my two 6581 as well? I can run on NTSC and PAL machines.

![IMG_0029](https://github.com/libsidplayfp/libsidplayfp/assets/2496353/727e7131-a5c5-4073-a923-641389143bbb)

**Comment by reFX-Mike** [comment]
I also have two 8580. So four SID overall I can use to create combined waveforms.

**Comment by drfiemost** [comment]
Well, the samplings look quite variable with no predictable pattern, but if you have some spare time you can run the following program, possibly on a warmed up chip:

https://github.com/daglem/reDIP-SID/blob/master/research/combsample.d64

Be warned:

> takes forever to run

**Comment by reFX-Mike** [comment]
Should I run that C64 program on a PAL or NTSC machine? Only for the 6581 or also fo the 8580?

**Comment by drfiemost** [comment]
> Slightly offtopic / ontopic https://www.youtube.com/watch?v=pePq68HaI7M

Interesting!

> Should I run that C64 program on a PAL or NTSC machine? Only for the 6581 or also fo the 8580?

PAL or NTSC should make no difference. The program is meant for the 6581, due to the topbit 'bug', but will also work for the 8580.

**Comment by drfiemost** [comment]
> Yes, it will work, but for NTSC, isn't the pitch different, thus the measurements might be off?

The delay is based on CPU cycles so the processor frequency doesn't matter
https://github.com/daglem/reDIP-SID/blob/master/research/combsample.a65

> Also, aren't we interested in capturing the 8580 combined waveforms too? Or is their behavior so well-defined that it's considered a solved problem?

The 8580 doesn't reset the topbit halfway through (see waveforms 3 and 6 [here](http://ploguechipsounds.blogspot.com/2010/03/sid-waveform-captures.html)) so it could be sampled with a faster routine, but this one will work too.

**Comment by drfiemost** [comment]
Yeah, there is a lot of variation between chips even for the same revision. Some chips have stronger or mellower combined waveforms but no definite pattern.

As I said if you have time to waste it's ok, but there are already a few samples available for the 6581 so it won't add much value.

**Comment by reFX-Mike** [comment]
Found a third one in my collection:

![6581R4AR](https://github.com/libsidplayfp/libsidplayfp/assets/2496353/2ca36a74-ec66-4127-b4d9-a3948d9ab591)
[6581R4AR - 3488 14.zip](https://github.com/libsidplayfp/libsidplayfp/files/13689345/6581R4AR.-.3488.14.zip)

The ZIP file contains the results for this 6581R4AR 3488 14

I will add the other two chips later. I also have a 6581 in an SX64, but I would need to disassemble it partially to gain access, as it's in an NTSC machine, and I prefer to run the program in my PAL C64 which has a ZIF socket.

BTW, I wouldn't call 10 minutes "FOREVER". Yes, it took 10 minutes. I had the chip warm up by running the program twice (deleting the result files in between, in case the tool doesn't overwrite them). The chip was nice and toasty by the second time it was run.

**Comment by reFX-Mike** [comment]
6581 2083

![6581 2083](https://github.com/libsidplayfp/libsidplayfp/assets/2496353/0b086b63-564a-4ec4-a120-e76eae17df18)
[6581 2083.zip](https://github.com/libsidplayfp/libsidplayfp/files/13690168/6581.2083.zip)

**Comment by drfiemost** [comment]
Thanks! Unfortunately the second one is all null.
Also if it doesn't take that long the 8580 are welcome too.

BTW I've added the sampling at https://github.com/libsidplayfp/combined-waveforms/tree/master/new
There is no evident pattern across revisions, all I can see is that the one labeled _locu128_6581_cbm_4383_ is somewhat weaker than the others.

**Comment by reFX-Mike** [comment]
Here is the 6581 - 1585

![6581 2083](https://github.com/libsidplayfp/libsidplayfp/assets/2496353/50ce2037-8120-4706-8ede-34e5c865535a)
[6581 1585.zip](https://github.com/libsidplayfp/libsidplayfp/files/13693856/6581.1585.zip)

**Comment by reFX-Mike** [comment]
>Thanks! Unfortunately the second one is all null.

I'll re-run the 2083 and check the files. Maybe it wasn't seated properly, but it's more likely somebody sold me a bunk chip.

I'll also still have to dig out the 6581 from the SX-64.

**Comment by reFX-Mike** [comment]
Ran it again, but it's still all zeros. It's dead :(

**Comment by reFX-Mike** [comment]
I ran the program with an 8580R5, but the filenames are still 6581wf30.dat, etc. Is that expected? Or does it fail detection? Or is there a combined waveform program specifically for the 8580?

**Comment by drfiemost** [comment]
The filenames are hardcoded but the data is still good.

**Comment by reFX-Mike** [comment]
Here's the 8580R5 5092 25

![8580R5 5092 25](https://github.com/libsidplayfp/libsidplayfp/assets/2496353/1cd8df8c-5279-4400-b462-4dc7d30f4478)
[8580R5 5092 25.zip](https://github.com/libsidplayfp/libsidplayfp/files/13697173/8580R5.5092.25.zip)

**Comment by reFX-Mike** [comment]
And here is my second 8580, which turns out to be the same revision, same week, and even the same lot number (if that is what the last number is).

[8580R5 5092 25  #2.zip](https://github.com/libsidplayfp/libsidplayfp/files/13697290/8580R5.5092.25.2.zip)

**Comment by drfiemost** [comment]
Done in 2.6, @reFX-Mike thanks for the samplings!
